---
  - name: Update dir.conf
    lineinfile:
      dest: /etc/apache2/mods-enabled/dir.conf
      regexp: ^DirectoryIndex
      line: "DirectoryIndex index.php index.html index.cgi index.pl index.xhtml index.htm"
    notify: restart apache2

