---
# tasks file for lamp
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: true

- name: Install required software
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes  
  vars:
    packages:
      - apache2
      - mysql-server
      - php
      - php-mysql
      - libapache2-mod-php
