---
# tasks file for php
  - name: Install php extensions
    apt:
      name: ['php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip']
      state: present
    notify: restart apache2
